export interface Opportunity {
  id: string;
  title: string;
  organization: string;
  category: "scholarship" | "bursary" | "grant" | "loan" | "research";
  fundingType: string;
  amount: string;
  deadline: string;
  status: "active" | "draft" | "closed";
  dateCreated: string;
  description: string;
  eligibility: string;
  requiredDocuments: string;
  applicationInstructions: string;
  featured: boolean;
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "Mastercard Foundation Scholars Program",
    organization: "Mastercard Foundation",
    category: "scholarship",
    fundingType: "Full Scholarship",
    amount: "MWK 2,500,000",
    deadline: "2026-04-15",
    status: "active",
    dateCreated: "2026-02-10",
    description: "A fully funded scholarship for academically talented yet economically disadvantaged students pursuing undergraduate degrees at Mzuzu University.",
    eligibility: "Must be a Malawian citizen, demonstrate financial need, maintain a GPA of 3.0 or above, and be enrolled full-time at Mzuzu University.",
    requiredDocuments: "National ID, Academic Transcripts, Proof of Income, Recommendation Letter, Personal Statement",
    applicationInstructions: "Complete the online application form, upload all required documents, and submit before the deadline. Shortlisted candidates will be contacted for interviews.",
    featured: true,
  },
  {
    id: "2",
    title: "Government of Malawi Bursary Scheme",
    organization: "Ministry of Education",
    category: "bursary",
    fundingType: "Partial Bursary",
    amount: "MWK 800,000",
    deadline: "2026-04-30",
    status: "active",
    dateCreated: "2026-01-20",
    description: "Government-funded bursary for needy students enrolled in public universities across Malawi.",
    eligibility: "Malawian citizens from low-income families, enrolled in a recognized public university, with a GPA of 2.5 or above.",
    requiredDocuments: "Student ID, Admission Letter, Income Declaration Form, Chiefs Letter",
    applicationInstructions: "Applications must be submitted through the university's financial aid office. Attach all supporting documents.",
    featured: false,
  },
  {
    id: "3",
    title: "UNICEF Youth Innovation Research Grant",
    organization: "UNICEF Malawi",
    category: "grant",
    fundingType: "Research Grant",
    amount: "MWK 1,200,000",
    deadline: "2026-05-20",
    status: "active",
    dateCreated: "2026-03-01",
    description: "Funding for student-led research projects focused on child welfare, education technology, or public health innovations in Malawi.",
    eligibility: "Undergraduate or postgraduate students with a research proposal approved by their department. Must focus on child welfare or education.",
    requiredDocuments: "Research Proposal, Ethical Clearance, Student ID, Department Approval Letter",
    applicationInstructions: "Submit a detailed research proposal with budget breakdown via the UNICEF Malawi portal. Proposals reviewed monthly.",
    featured: true,
  },
  {
    id: "4",
    title: "National Bank of Malawi Student Loan",
    organization: "National Bank of Malawi",
    category: "loan",
    fundingType: "Student Loan",
    amount: "MWK 1,500,000",
    deadline: "2026-06-01",
    status: "draft",
    dateCreated: "2026-03-10",
    description: "Low-interest student loan facility for Malawian university students to cover tuition and living expenses.",
    eligibility: "Must have a guarantor, be enrolled at a recognized university, and provide proof of enrollment.",
    requiredDocuments: "Guarantor Form, Admission Letter, National ID, Bank Statements",
    applicationInstructions: "Visit any National Bank branch to pick up an application form. Submit completed forms with all required documents to the student loans department.",
    featured: false,
  },
  {
    id: "5",
    title: "African Leadership Academy Fellowship",
    organization: "African Leadership Academy",
    category: "scholarship",
    fundingType: "Full Fellowship",
    amount: "MWK 3,000,000",
    deadline: "2026-03-28",
    status: "active",
    dateCreated: "2026-01-05",
    description: "A prestigious fellowship for emerging African leaders pursuing studies in governance, entrepreneurship, and community development.",
    eligibility: "Students aged 18-25 with demonstrated leadership experience. Must submit a leadership portfolio.",
    requiredDocuments: "CV, Leadership Portfolio, Academic Transcripts, Two Reference Letters, Personal Essay",
    applicationInstructions: "Apply online through the ALA portal. Include your leadership portfolio and personal essay. Finalists will attend a selection bootcamp.",
    featured: true,
  },
  {
    id: "6",
    title: "COSOMA Arts & Culture Bursary",
    organization: "Copyright Society of Malawi",
    category: "bursary",
    fundingType: "Partial Bursary",
    amount: "MWK 500,000",
    deadline: "2026-03-10",
    status: "closed",
    dateCreated: "2025-12-15",
    description: "Bursary for students studying creative arts, music, or cultural studies at Malawian universities.",
    eligibility: "Must be enrolled in a creative arts, music, or cultural studies program. Preference given to students with a demonstrated portfolio.",
    requiredDocuments: "Student ID, Portfolio Samples, Enrollment Letter, Personal Statement",
    applicationInstructions: "Submit your application via the COSOMA website along with portfolio samples and academic records.",
    featured: false,
  },
  {
    id: "7",
    title: "Mzuzu University Research Support Fund",
    organization: "Mzuzu University",
    category: "research",
    fundingType: "Research Support",
    amount: "MWK 600,000",
    deadline: "2026-07-15",
    status: "draft",
    dateCreated: "2026-03-18",
    description: "Internal research funding for postgraduate students conducting thesis or dissertation research aligned with university strategic priorities.",
    eligibility: "Registered postgraduate students at Mzuzu University. Research must align with the university's strategic research areas.",
    requiredDocuments: "Research Proposal, Supervisor Endorsement, Enrollment Verification, Budget Plan",
    applicationInstructions: "Submit proposals to the Directorate of Research and Publications. Proposals are reviewed quarterly.",
    featured: false,
  },
  {
    id: "8",
    title: "World Bank HESP Scholarship",
    organization: "World Bank",
    category: "scholarship",
    fundingType: "Full Scholarship",
    amount: "MWK 4,000,000",
    deadline: "2026-05-31",
    status: "active",
    dateCreated: "2026-02-28",
    description: "Higher Education Support Program scholarship for students in STEM and agriculture fields at public universities in Malawi.",
    eligibility: "Enrolled in STEM or agriculture programs. Must demonstrate academic excellence and financial need.",
    requiredDocuments: "Academic Transcripts, Financial Need Statement, National ID, Recommendation Letters",
    applicationInstructions: "Apply through the Ministry of Education's online portal. Include all transcripts and need statements.",
    featured: true,
  },
];
